\input libspacetime
@settitle libspacetime Documentation

@copying
TODO
@end copying

@titlepage
@title libspacetime Documentation
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@node Top
@top libspacetime: timekeeping beyond Earth

This is the libspacetime documentation manual.

@menu
* Overview::   About libspacetime and its goals.
* Earth::   Documentation for timekeeping on Earth.
* Mars::    Documentation for timekeeping on Mars.
* Index::   Complete index.
* Function Index::   Complete function index.
@end menu


@node Overview
@chapter Overview
@section Welcome
@nodedescription Welcome to libspacetime!

libspacetime is a cross-platform library for date and time operating
across multiple planets, while matching the current standards and
specifications for date and time functions as best as possible.

Currently, only Mars is supported. Other planets may be supported in
the future. (Of course, this may be difficult, as years become longer
the farther the planets are from the sun. But maybe other systems,
being relative to a planet's moons or systems of other orbital bodies
could be considered).

@node Philosophy
@section Philosophy

When initially creating this library, there was the question of "why?".
After all, it was 2026, and no standard for timekeeping beyond Earth
had been created.

That year, the Artemis II mission was a success. The later goals of the
Artemis mission is to setup a moon base to then be used to bring humans
to Mars.

It was the perfect time to start preparing computers to assist humanity
with timekeeping on Mars. The Darian Calendar system, has been notable
enough to have its own Wikipedia page, and there are various
implementations in other programming languages, but not in C.

Again, although the Darian Calendar had not been declared "official",
it seemed to have the most potential.

Thomas Gangale, who proposed the Darian Calendar, also proposed a
system for Jupiter and Titan. Although those would definitely be years
away, and likely work differently due to the length of orbit, there was
thought being put into humans tracking time in space. For this reason,
the library was named "libspacetime" instead of "libdarian" to allow
for future expansion.

In the more immediate future, the reasoning for a C implementation of
the Darian Calendar would allow for integration with other parts of
a UNIX-based system, and eventually, all other kinds of software.
Language bindings could be made to work with space time at a performant
low level.

In addition, to help ease support of developers adopting the new
calendar system, the library would conform to existing practices and
APIs to make its use trivial. For C programs, it would be as if they
were calling functions directly from the C standard library, although
they are not. This allows for the "proposed" time systems to be
separate from the existing, relevant, and more important Earth systems
in the C standard library.

Timekeeping for Mars would be alongside timekeeping for Earth, and make
tracking both easy. The idea of timekeeping for Mars has not been
exclusive to hobbyists or thinkers: NASA has included a local clock for
certain locations in Mars24. With other calendar systems being
developed beyond Mars, it makes sense to lay the foundation for future
timekeeping in a way that is similar to what humans are already
familiar with.

@node Practices
@section Practices

@subsection Standard Compliance

Since the goal of libspacetime is to provide timekeeping for other
planets while being as conformant as possible to existing standards,
any non-deprecated function will get its implementation in the other
timekeeping system.

@c TODO: Go into detail about ISO C and whatnot.

@subsection Portability

libspacetime should attempt to be as portable as possible, and work on
as many systems as possible. This may be difficult given mathematical
requirements, like needing to use double floating-point precision for
calculations, but best effort will be made.

@subsection Dependencies

libspacetime should try to be as easy to build, test, and use on any
device. Dependencies should be minimized as much as possible. Any
dependency should not be something required for a system to have.

If a dependency is added, there should be an option, if possible, to
not use that dependency, via providing another implementation or an
alternative method of achieving the intended functionality.

@subsection Autotools

For the previous subsection on dependencies, libspacetime uses
Autotools as its build system. Tests use the Autotest system, although
it is a bit clunky. The reasoning is that any system capable of
compiling other libraries should not have to install other tooling to
use libspacetime. Autotools is old enough and respected that most
platforms should be able to work with it, and most systems should be
able to install it with no issue.

@subsection Texinfo for Documentation

Just like Autotools, the usage of Texinfo for documentation is due to
its long history and use for info pages.

@subsection Unix Philosophy and Simplicity

The Unix Philosophy is applied as much as possible, along with the
following other ideas:

@bullet{} KISS (Keep it simple stupid)

@bullet{} Less is more.

Design and program with care, thoughtfulness, testing, and
documentation :)

@include earth.texi
@include mars.texi
@include index.texi

@bye
