@node Mars
@chapter Mars
@nodedescription Documentation for timekeeping on Mars

@menu
* Definitions for Mars:: Useful definitions.
* Darian Calendar:: An introduction to the Darian Calendar system.
* Types:: Types for working with Martian time.
* Numerical time functions:: Functions for working with numerical
representations
* String functions:: Functions for working with string representations
* Conversion functions:: Functions for converting between planets
@end menu

@node Definitions for Mars
@section Definitions
@nodedescription Useful definitions.

There is some special language used around timekeeping on Mars.

@cindex Martian Sol
@dfn {Martian Sol}
A day on Mars - that is, the amount of time it takes for Mars
to complete its rotation.

@cindex MSD: Mars Sol Date
@dfn {MSD: Mars Sol Date}
The amount of sols since approximately 12:00 UTC, December 29th 1873 on Earth.

@node Darian Calendar
@section Darian Calendar
@nodedescription An introduction to the Darian Calendar system.

@c TODO hyperlinks, fill out section.
The Darian Calendar is a proposed calendar system for Mars by Thomas
Gangale.

There is a website that lists all the information, including a date
conversion tool.

As a brief overview, the year has 24 months. Each year contains four
seasons. Each month is 28 sols, except for the last month of the
season, which contains 27 sols. The only exception is the last month
of the year, Vrishika, when the year is a leap year.

Leap years occur when the year is an odd number, or divisible by 10
unless the year is also divisible by 100. So, for example, the years
191, 193, and 195 are leap years. 190 is also a leap year as it is
divisible by 10. The year 200, however, is not a leap year, as it is
divisible by 100.

The month names are as follows:

@enumerate
@item
Sagittarius
@item
Dhanus
@item
Capricornus
@item
Makara
@item
Aquarius
@item
Kumbha
@item
Pisces
@item
Mina
@item
Aries
@item
Mesha
@item
Taurus
@item
Rishabha
@item
Gemini
@item
Mithuna
@item
Cancer
@item
Karka
@item
Leo
@item
Simha
@item
Virgo
@item
Kanya
@item
Libra
@item
Tula
@item
Scorpius
@item
Vrishika
@end enumerate

And the sol names of the week are as follows:
@enumerate
@item
Solis
@item
Lunae
@item
Martis
@item
Mercurii
@item
Jovis
@item
Veneris
@item
Saturni
@end enumerate

@node Types
@section Types for Mars
@nodedescription Types for working with Mars time.

@c AI disclosure: searched up which commands to use
@deftp {Data type} mars_time_t
Represents the number of Martian seconds since approximately 12:00 UTC,
December 29th 1873, or Virgo 25th 140. When using, be aware that
mars_time_t should not be confused with time_t. Early values of
mars_time_t will represent negative time_t values as it predates the
Unix Epoch.
@end deftp

@deftypevr {Struct} struct mars_tm
The **mars_tm** structure is similar to the **tm** structure, which
represents "broken-down" time.
@deftypevar {int} mars_tm_sec
Martian seconds, 0-59
@end deftypevar
@deftypevar {int} mars_tm_min
Minutes, 0-59
@end deftypevar
@deftypevar {int} mars_tm_hour
Hours, 0-23
@end deftypevar
@deftypevar {int} mars_tm_msol
Sol of month, 1-28
@end deftypevar
@deftypevar {int} mars_tm_mon
Month, 0-23
@end deftypevar
@deftypevar {int} mars_tm_year
Year, starting from Darian Calendar Year 0
@end deftypevar
@deftypevar {int} mars_tm_wsol
Sol of week, 0-6
@end deftypevar
@deftypevar {int} mars_tm_ysol
Sol of year, 0-668
@end deftypevar

@end deftypevr

@node Numerical time functions
@section Numerical time functions for Mars
@nodedescription TODO

@c surely there's a better way to do this
@defun ammarstime (mars_time_t* @var{timer})
Analagous to gmtime. Returns a broken down time structure
(struct mars_tm) representing the amount of time since the time stored
in @var{TIMER}.

WARNING: Probably due to float modulus operations, there appears
to be usually 1-2, but sometimes up to 4 seconds of variance in
conversions. This is being investigated.
@end defun

@defun diffmarstime (mars_time_t @var{time_end}, mars_time_t @var{time_start})
Returns the amount of time since time_end and time_start.

It is literally basic subtraction.

This function exists for the sake of matching "standards" because the
difftime function exists.
@end defun

@defun localmarstime (mars_time_t* @var{timer})
The same as ammarstime, except returns the time relative to the
timezone.

NOTE: Timezones are currently unimplemented. This returns MTC for now.
@end defun

@defun mars_time (mars_time_t* @var{timer})
Returns the current value of time elapsed in Martian seconds since MSD
0, and sets @var{timer} to that value if not NULL.
@end defun

@defun mkmarstime (struct mars_tm* @var{tm})
Returns the number of Martian Seconds (mars_time) given the broken down
time structure in @var{tm}.

If @var{tm} is NULL, -1 is returned.
@end defun

@node String functions
@section String functions for Mars
@nodedescription Functions for working with string representation. TODO

@defun strfmarstime (char* @var{s}, size_t @var{count}, char* @var{format}, struct mars_tm* @var{tm})
Returns a string format representation of a broken down time structure
(@var{tm}).

This is the equivalent of the strftime function.

@c TODO: explain format specifiers
@end defun

@defun strpmarstime (char* @var{str}, char* @var{format}, struct mars_tm* @var{tm})
Parses a string format representation of a broken down time structure
(@var{tm}).

This is the inverse of strfmarstime.

This is the equivalent of the strptime function.
@c TODO: fill
@end defun


@defun wcsfmarstime (wchar_t* @var{wcs}, size_t @var{count}, wchar_t* @var{format}, struct mars_tm* @var{tm})
This is the same as strfmarstime but for wide characters (wchar_t).

This is the equivalent of the wcsftime function.
@c TODO: that is basically it right?
@end defun

@node Conversion functions
@section Conversion functions
@strong {WARNING: Still a work in progress.}

These are functions that can be used to convert between timekeeping
systems.

@strong {THESE NAMES ARE ESPECIALLY SUBJECT TO CHANGE!}

@defun earth_time_to_msd(time_t @var{et})
Calculates the MSD (Mars Sol Date) given the amount of seconds since
the Unix Epoch (@var{et}).

If programming in C, use of this function is discouraged. It is for use
in a Python binding for libspacetime to match the behavior of Python's
time function, which returns time as a floating point number instead of
an integer.
@end defun

@defun earth_time_to_mars_time(time_t @var{et})
Converts Earth Time (@var{et}) to Martian Time, represented
in seconds since MSD 0.
@end defun

@defun mars_time_to_earth_time(mars_time_t @var{mars_time})
Converts Martian Time (@var{mars_time}) to Earth Time, represented
in seconds since the Unix Epoch.
@end defun
